Sprint 3
thechertan/middle.messenger.praktikum.yandex pull request #5
Opened 2022-10-12 22:24 UTC by thechertan

2022-10-29 05:52 UTC, podlovchenko requested changes
Доброе утро!)

Круто, что есть алиасы 👍 

Есть замечания по работе системы
1. Нет редиректа на страницу чатов, если пользователь уже в системе
2. На страницу регистрации все время ошибка "пароли не совпадают", в validateInput не передается text2 для сравнения
3. При обновлении страницы Cannot GET /sign-up
По заданию  
<img width="736" alt="Снимок экрана 2022-10-29 в 08 43 06" src="https://user-images.githubusercontent.com/22602747/198815950-58240f5d-7ecf-4caf-9195-ba857683845d.png">
4. Много ошибок линтера и типизации, попробуй выполнить команду `tsc --noEmit`

2022-10-29 05:52 UTC, podlovchenko commented on src/blocks/chat/__list-item/chat__list-item.css
> +  border-top: 1px solid #eaeaea;
Цвета лучше указывать через css переменные, так будет понятнее, что это за цвет при просмотре кода и проще редактировать цвета по всему проекту
https://developer.mozilla.org/ru/docs/Web/CSS/Using_CSS_custom_properties

2022-10-29 05:52 UTC, podlovchenko commented on src/components/chat/__profile/chat-profile.ts
> +    super({ ...props });
```suggestion
  constructor(props) {
    super(props);

```

2022-10-29 05:52 UTC, podlovchenko commented on package.json
> +    "@anikin/parcel-transformer-handlebars": "^1.0.2",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-10-29 05:52 UTC, podlovchenko commented on src/utils/api/auth/AuthApi.ts
> +  signUp({ ...props }: SignupOptions): Promise<any> {
Было бы отлично определить типы возвращаемых значений

2022-10-29 05:52 UTC, podlovchenko commented on src/utils/api/auth/AuthApi.ts
> +    const data = JSON.stringify({ ...props });
Можно просто
```suggestion
  signUp(props: SignupOptions): Promise<any> {
    const data = JSON.stringify(props);
```

2022-10-29 05:52 UTC, podlovchenko commented on src/utils/api/auth/AuthApi.ts
> +      },
Лучше внести внутрь HTTPTransport и добавлять в зависимости от типа data

2022-10-29 05:52 UTC, podlovchenko commented on src/utils/api/auth/AuthApi.ts
> +      withCredentials: true,
Используется в каждом запросе, лучше внести внутрь HTTPTransport

2022-10-30 19:43 UTC, podlovchenko requested changes
Привет, файлов .js и .js.map не должно быть в проекте
При переходи в профиль `Cannot GET /settings`

2022-10-30 19:43 UTC, podlovchenko commented on src/components/chat/__list-users/_item/_click/chat-list-click.js.map
> +{"version":3,"file":"chat-list-click.js","sourceRoot":"","sources":["chat-list-click.ts"],"names":[],"mappings":";;;;;;;;;;;;;;AAAA,+BAA6B;AAQ7B,MAAa,aAAc,SAAQ,YAAK;IAGtC,YAAY,EAAyC;YAAzC,EAAE,WAAW,O
Файлов .map не должно быть в репозитории

2022-10-30 21:21 UTC, thechertan commented on src/components/chat/__list-users/_item/_click/chat-list-click.js.map
> +{"version":3,"file":"chat-list-click.js","sourceRoot":"","sources":["chat-list-click.ts"],"names":[],"mappings":";;;;;;;;;;;;;;AAAA,+BAA6B;AAQ7B,MAAa,aAAc,SAAQ,YAAK;IAGtC,YAAY,EAAyC;YAAzC,EAAE,WAAW,O
При переходи в профиль Cannot GET /settings

Странно, у меня работает,
![image](https://user-images.githubusercontent.com/84693047/198902120-19a3584b-10a3-4a73-91c9-8eaafadf420d.png)

2022-10-30 23:47 UTC, thechertan commented on src/components/chat/__list-users/_item/_click/chat-list-click.js.map
> +{"version":3,"file":"chat-list-click.js","sourceRoot":"","sources":["chat-list-click.ts"],"names":[],"mappings":";;;;;;;;;;;;;;AAAA,+BAA6B;AAQ7B,MAAa,aAAc,SAAQ,YAAK;IAGtC,YAAY,EAAyC;YAAzC,EAAE,WAAW,O
как я понял, вы запускаете проект через express, однако в тз не сказано делать в express роутинг.
Т.Е use('/settings' static folder) или я ошибаюсь? роутинг сделан только в части frontEnd

Запустите проект через npm run dev 
для netlify я сделал 

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = false

2022-10-31 00:14 UTC, thechertan commented on src/components/chat/__list-users/_item/_click/chat-list-click.js.map
> +{"version":3,"file":"chat-list-click.js","sourceRoot":"","sources":["chat-list-click.ts"],"names":[],"mappings":";;;;;;;;;;;;;;AAAA,+BAA6B;AAQ7B,MAAa,aAAc,SAAQ,YAAK;IAGtC,YAAY,EAAyC;YAAzC,EAAE,WAAW,O
![image](https://user-images.githubusercontent.com/84693047/198908909-33477900-5878-489f-9044-b07d592064ba.png)

2022-10-31 07:38 UTC, podlovchenko commented on src/components/chat/__list-users/_item/_click/chat-list-click.js.map
> +{"version":3,"file":"chat-list-click.js","sourceRoot":"","sources":["chat-list-click.ts"],"names":[],"mappings":";;;;;;;;;;;;;;AAAA,+BAA6B;AAQ7B,MAAa,aAAc,SAAQ,YAAK;IAGtC,YAAY,EAAyC;YAAzC,EAAE,WAAW,O
Попробуй запустить npm run start, в этом случае не работает
Необходимо добавить в сервер
```
app.get('*', (req, res) => {
  res.sendFile(...) // путь до index.html
})
```

2022-10-31 19:34 UTC, podlovchenko commented on app.js
> -app.use(express.static('dist'));
Отдача статики тоже нужна, сейчас открывается белый экран

2022-11-01 07:57 UTC, podlovchenko commented
Работу принимаю)

2022-11-05 15:33 UTC, merged